name: Nix

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Nix Flake - Linux
    permissions:
      contents: read
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Clone project
        uses: actions/checkout@v5
      - name: Build
        # "nix build" builds with full optimization and includes a profiling
        # build, so just the build of xmonad-contrib itself takes 3 minutes.
        # As a workaround, we invoke cabal manually here.
        run: |
          nix develop -c cabal v2-update -O0 -j
          nix develop -c cabal v2-build -O0 -j
